parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

extends: 'htmlacademy/node'

globals:
  _f: true

rules:
  arrow-spacing: 'error'
  comma-dangle: ['error', 'always-multiline']
  complexity: ['error', 7]
  implicit-arrow-linebreak: ['error', 'beside']
  indent: ['error', 2]
  max-depth: ['error', 2]
  max-len: ['error', { 'code': 101 }]
  max-lines: ['error', 223]
  max-params: ['error', 5]
  max-statements: ['error', 16, { 'ignoreTopLevelFunctions': true }]
  no-await-in-loop: 'error'
  no-confusing-arrow: 'error'
  no-extra-parens: 'error'
  no-magic-numbers: ['error', { 'ignore': [0, 1] }]
  no-return-await: 'error'
  object-property-newline: 'error'
  padded-blocks: ['error', 'never']
  padding-line-between-statements: ['error', { blankLine: 'never', prev: '*', next: 'return' }]
  prefer-arrow-callback: 'error'
  prefer-const: 'error'
  prefer-template: 'error'
  require-await: 'error'
  template-curly-spacing: 'error'
  vars-on-top: 'error'
  no-return-assign: 'error'

overrides:
  - files: '*.e2e.js'
    globals:
      request: true
  - files: ['*.e2e.js', './config/constants.js']
    rules:
      no-magic-numbers: 'off'
